### ISSUE TITLE
ETCopyData:full exits unexpectedly after "sObjects should be processed in this order:"

### ISSUE THREAD

**Issue by jeremyhiggs** [eltoroit/ETCopyData#23] opened 2019-07-31 07:50 UTC
I'm receiving this error when trying to run ETCopyData:full:
> 07:46:40.801Z  63  TRACE  Importer.js:69        sObjects should be processed in this order:

This happens whether there are 5 custom sObjects (with relationships) or a single object with no relationships!

Here is the config file:
```
{
    "now": "2019-07-31T07:49:30.982Z",
    "orgSource": "jhiggs@ecoenergyfinance.org",
    "orgDestination": "ecoenergy_scratch",
    "sObjectsData": [
        {
            "name": "District__c",
            "ignoreFields": "OwnerId,CreatedBy,CreatedDate,CurrencyIsoCode,LastModifiedBy,LastModifiedDate",
            "maxRecords": -1,
            "orderBy": null,
            "where": null
        }
    ],
    "sObjectsMetadata": [
        {
            "name": "District__c",
            "fieldsToExport": "Id,Name",
            "matchBy": "Name",
            "orderBy": null,
            "where": null
        }
    ],
    "rootFolder": "sfdx-data",
    "includeAllCustom": false,
    "stopOnErrors": true,
    "ignoreFields": "OwnerId, CreatedBy, CreatedDate, CurrencyIsoCode, LastModifiedBy, LastModifiedDate",
    "maxRecordsEach": null,
    "deleteDestination": true,
    "pollingTimeout": 100000
}
```

And the output:
```
Timestamp      #   Level  Line Number           Description
─────────────  ──  ─────  ────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
07:49:30.971Z  1   TRACE  ETCopyData.js:17      Log level: TRACE
07:49:30.974Z  2   INFO   ETCopyData.js:19      ETCopyData:Full Process Started
07:49:30.977Z  3   INFO   Settings.js:289       Configuration value for [orgSource]: jhiggs@ecoenergyfinance.org
07:49:30.977Z  4   INFO   Settings.js:289       Configuration value for [orgDestination]: ecoenergy_scratch
07:49:30.978Z  5   INFO   Settings.js:289       Configuration value for [stopOnErrors]: true
07:49:30.978Z  6   INFO   Settings.js:289       Configuration value for [rootFolder]: sfdx-data
07:49:30.978Z  7   INFO   Settings.js:289       Configuration value for [ignoreFields]: OwnerId, CreatedBy, CreatedDate, CurrencyIsoCode, LastModifiedBy, LastModifiedDate
07:49:30.978Z  8   INFO   Settings.js:289       Configuration value for [deleteDestination]: true
07:49:30.978Z  9   INFO   Settings.js:289       Configuration value for [pollingTimeout]: 100000
07:49:30.979Z  10  INFO   Settings.js:225       Configuration value for [sObjectsData]: 1 sObjects found.
07:49:30.979Z  11  INFO   Settings.js:232       Configuration value for [sObjectsMetadata]: 1 sObjects found.
07:49:30.984Z  12  TRACE  ETCopyData.js:271     Configuration settings read.
07:49:32.768Z  13  INFO   OrgManager.js:27      [jhiggs@ecoenergyfinance.org] Alias for username: [jhiggs@ecoenergyfinance.org]
07:49:36.967Z  14  INFO   OrgManager.js:27      [ecoenergy_scratch] Alias for username: [test-fnaodb12gvvu@example.com]
07:49:40.125Z  15  TRACE  Exporter.js:45        [ecoenergy_scratch] Querying Metadata sObject [District__c]
07:49:40.126Z  16  TRACE  Exporter.js:111       [ecoenergy_scratch] Querying [District__c] with SOQL: [SELECT Id,Name FROM District__c ]
07:49:41.402Z  17  INFO   Exporter.js:69        [ecoenergy_scratch] Queried [District__c], retrieved 0 records
07:49:41.412Z  18  TRACE  Exporter.js:45        [jhiggs@ecoenergyfinance.org] Querying Metadata sObject [District__c]
07:49:41.412Z  19  TRACE  Exporter.js:111       [jhiggs@ecoenergyfinance.org] Querying [District__c] with SOQL: [SELECT Id,Name FROM District__c ]
07:49:42.671Z  20  INFO   Exporter.js:69        [jhiggs@ecoenergyfinance.org] Queried [District__c], retrieved 15 records
07:49:42.675Z  21  TRACE  Importer.js:69        sObjects should be processed in this order:
```

Is this a configuration issue (my fault) or a bug?

**Comment by eltoroit** [comment] 2019-07-31 17:02
That is not an error, but just information. The weird part is that the objects are not listed in order. What happens after this line?

**Comment by jeremyhiggs** [comment] 2019-07-31 17:10
It exits to the shell!

**Comment by eltoroit** [comment] 2019-09-26 16:24
Is "District__c" a data or metadata object? It should not be included in both!

**Comment by eltoroit** [comment] 2019-09-26 16:28
I this the issue is configuration. I'm closing this issue.

**Closed by eltoroit** 2019-09-26 16:28 UTC

**Comment by jeremyhiggs** [comment] 2019-10-01 07:17
It was a while back, so I don't recall. Will check and let you know if I can't figure it out.

Having an error message would definitely help, though.
